on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ECR_REPOSITORY: myproject           # set this to your Amazon ECR repository name
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: MY_CONTAINER_NAME    
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: "14.x"
        
        
    - name: Install dependencies
      run: npm install
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ${{ env.AWS_REGION }}
       
    - name: clone repo
      run: git clone https://github.com/pavankumarkatikam/terraform-demo.git
      
    - name: clone repo
      run: ls
    
    - name: terraform init
      run: terraform init terraform-demo/
    
    - name: terraform apply
      run: terraform apply terraform-demo/
